### ISSUE TITLE
[Feature request] Add support for transparent proxies in UDP (TPROXY)

### ISSUE THREAD

**Issue by alpominth** [koro666/xsocket#1]
Unfortunately, xsocket doesn't work with transparent forwarders that use TPROXY targets in UDP ports, such as [ipt2socks](https://github.com/zfl9/ipt2socks).

Please, implement this kind of support in xsocket.

Is somewhat easy to implement, just track **IP_TRANSPARENT**, **IP_RECVORIGDSTADDR**, **IPV6_TRANSPARENT** and **IPV6_RECVORIGDSTADDR** and apply the options in the sockets

```
  setsockopt(new_sockfd, IPPROTO_IP, IP_TRANSPARENT, s, sizeof(s));
  setsockopt(new_sockfd, IPPROTO_IP, IP_RECVORIGDSTADDR, s, sizeof(s));
  setsockopt(new_sockfd, IPPROTO_IP, IPV6_TRANSPARENT, s, sizeof(s));
  setsockopt(new_sockfd, IPPROTO_IP, IPV6_RECVORIGDSTADDR, s, sizeof(s));
```

This piece of code can serve as a basis: https://github.com/zfl9/ipt2socks/blob/master/src/netutils.c

**Comment by alpominth** [comment]
Sorry, I made some tests and yes, xsocket work FINE with TPROXY UDP proxying. The "problem" is with transparent proxy program that refuses TPROXY connections inside network namespaces, I need to investigate this a little more.

Thanks.

**Comment by koro666** [comment]
All socket options are copied over from the old socket to the old one, provided it's possible to read the old value.

**Comment by alpominth** [comment]
I noticed that xsocket works very well with VRFs (Virtual Routing and Forwarding).

Just run xsocket-server inside a VRF and load libxbind.so in the program in the same way if it were with a netns.
